<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>Harness.NoInputSystem.Consumer</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>$(ExtraDefines)</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Consumer.cs" />
    <ProjectReference Include="../../Core/Core.csproj" />
    <ProjectReference Include="../../Remote/Remote.csproj" />
    <ProjectReference Include="../../UI/UI.csproj" />
  </ItemGroup>
</Project>
