<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>Nesh.MasterMemoryDebugger.UI</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>$(ExtraDefines)</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(PackageRoot)Runtime/UI/**/*.cs" />
    <ProjectReference Include="../Core/Core.csproj" />
    <ProjectReference Include="../Remote/Remote.csproj" />
    <ProjectReference Include="../Stubs/Stubs.csproj" />
  </ItemGroup>
</Project>
