using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security;
using System.Text;
using MasterMemory;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEditor.UnityLinker;

namespace Nesh.MasterMemoryDebugger.Editor
{
    /// <summary>
    /// Development builds only: keeps every member of the <c>[MemoryTable]</c> records and of the generated
    /// MemoryDatabase / ImmutableBuilder from managed code stripping, because the debugger reads and sets them through
    /// reflection (and calls Diff / Build / Validate for <see cref="MasterMemoryDebugRebuild"/>).
    /// Release builds are not affected. Unity ignores link.xml files inside packages, so the file is generated here.
    /// </summary>
    sealed class MasterMemoryDebuggerLinkerProcessor : IUnityLinkerProcessor
    {
        const string OutputPath = "Temp/MasterMemoryDebugger/link.xml";

        public int callbackOrder => 0;

        public string GenerateAdditionalLinkXmlFile(BuildReport report, UnityLinkerBuildPipelineData data)
        {
            if ((report.summary.options & BuildOptions.Development) == 0) return null;
            var settings = MasterMemoryDebuggerSettingsProvider.FindSettingsAsset();
            if (settings != null && !settings.Enabled) return null;

            var types = CollectTypes();
            if (types.Count == 0) return null;

            var path = Path.GetFullPath(OutputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(path));
            File.WriteAllText(path, CreateLinkXml(types));
            return path;
        }

        /// <summary>Records, generated databases and builders; generic definitions are skipped.</summary>
        internal static List<Type> CollectTypes()
        {
            var types = new HashSet<Type>();
            types.UnionWith(TypeCache.GetTypesWithAttribute<MemoryTableAttribute>());
            types.UnionWith(TypeCache.GetTypesDerivedFrom<MemoryDatabaseBase>());
            types.UnionWith(TypeCache.GetTypesDerivedFrom<ImmutableBuilderBase>());
            return types.Where(x => !x.IsGenericTypeDefinition && !x.IsAbstract).ToList();
        }

        internal static string CreateLinkXml(IEnumerable<Type> types)
        {
            var sb = new StringBuilder();
            sb.AppendLine("<linker>");
            sb.AppendLine("  <!-- Generated by MasterMemory Debugger for development builds. -->");
            foreach (var assembly in types.GroupBy(x => x.Assembly.GetName().Name).OrderBy(x => x.Key, StringComparer.Ordinal))
            {
                sb.Append("  <assembly fullname=\"").Append(SecurityElement.Escape(assembly.Key)).AppendLine("\">");
                foreach (var type in assembly.OrderBy(x => x.FullName, StringComparer.Ordinal))
                {
                    // nested types are written Outer/Inner in link.xml
                    var name = type.FullName.Replace('+', '/');
                    sb.Append("    <type fullname=\"").Append(SecurityElement.Escape(name)).AppendLine("\" preserve=\"all\" />");
                }
                sb.AppendLine("  </assembly>");
            }
            sb.AppendLine("</linker>");
            return sb.ToString();
        }
    }
}
