<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>Nesh.MasterMemoryDebugger.Runtime</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>$(ExtraDefines)</DefineConstants>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(PackageRoot)Runtime/**/*.cs" />
    <ProjectReference Include="../Stubs/Stubs.csproj" />
    <PackageReference Include="MasterMemory" Version="3.0.4" />
  </ItemGroup>
</Project>
