<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>Nesh.MasterMemoryDebugger.InputSystem</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>$(ExtraDefines)</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(PackageRoot)Runtime/InputSystem/**/*.cs" />
    <ProjectReference Include="../UI/UI.csproj" />
    <ProjectReference Include="../Stubs/Stubs.csproj" />
    <ProjectReference Include="../InputSystemStubs/InputSystemStubs.csproj" />
  </ItemGroup>
</Project>
